### ISSUE TITLE
Threshold Bar Start range as value issue

### ISSUE THREAD

**Issue by elangovis** [predixdesignsystem/px-threshold-bar#2]
When the start range and value are same the value appears in the middle instead of start of threshold bar.

![image](https://user-images.githubusercontent.com/26504841/48847732-3dbf7600-edc8-11e8-883e-252d4e0bf291.png)

Need this to be fixed as this component is used in production of Realtrack tool

**Comment by evanjd** [comment]
Thanks for raising this @elangovis. This has now been resolved. Updated version is [v1.0.4](https://github.com/predixdesignsystem/px-threshold-bar/releases/tag/v1.0.4).
